// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/types.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types/types.proto

It has these top-level messages:
	CreateDotTx
	DotState
*/
package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CreateDotTx struct {
	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	R uint32 `protobuf:"varint,3,opt,name=r,proto3" json:"r,omitempty"`
	G uint32 `protobuf:"varint,4,opt,name=g,proto3" json:"g,omitempty"`
	B uint32 `protobuf:"varint,5,opt,name=b,proto3" json:"b,omitempty"`
}

func (m *CreateDotTx) Reset()                    { *m = CreateDotTx{} }
func (m *CreateDotTx) String() string            { return proto.CompactTextString(m) }
func (*CreateDotTx) ProtoMessage()               {}
func (*CreateDotTx) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

func (m *CreateDotTx) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CreateDotTx) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *CreateDotTx) GetR() uint32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *CreateDotTx) GetG() uint32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *CreateDotTx) GetB() uint32 {
	if m != nil {
		return m.B
	}
	return 0
}

type DotState struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Uuid  string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	X     uint32 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y     uint32 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	R     uint32 `protobuf:"varint,5,opt,name=r,proto3" json:"r,omitempty"`
	G     uint32 `protobuf:"varint,6,opt,name=g,proto3" json:"g,omitempty"`
	B     uint32 `protobuf:"varint,7,opt,name=b,proto3" json:"b,omitempty"`
}

func (m *DotState) Reset()                    { *m = DotState{} }
func (m *DotState) String() string            { return proto.CompactTextString(m) }
func (*DotState) ProtoMessage()               {}
func (*DotState) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

func (m *DotState) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DotState) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *DotState) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *DotState) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *DotState) GetR() uint32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *DotState) GetG() uint32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *DotState) GetB() uint32 {
	if m != nil {
		return m.B
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateDotTx)(nil), "CreateDotTx")
	proto.RegisterType((*DotState)(nil), "DotState")
}

func init() { proto.RegisterFile("types/types.proto", fileDescriptorTypes) }

var fileDescriptorTypes = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0xc1, 0x5c, 0xdc, 0xce, 0x45,
	0xa9, 0x89, 0x25, 0xa9, 0x2e, 0xf9, 0x25, 0x21, 0x15, 0x42, 0x3c, 0x5c, 0x8c, 0x15, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x8c, 0x60, 0x5e, 0xa5, 0x04, 0x13, 0x84, 0x57, 0x09, 0xe2, 0x15,
	0x49, 0x30, 0x43, 0x78, 0x45, 0x20, 0x5e, 0xba, 0x04, 0x0b, 0x84, 0x97, 0x0e, 0xe2, 0x25, 0x49,
	0xb0, 0x42, 0x78, 0x49, 0x4a, 0x55, 0x5c, 0x1c, 0x2e, 0xf9, 0x25, 0xc1, 0x25, 0x89, 0x25, 0xa9,
	0x42, 0x22, 0x5c, 0xac, 0xf9, 0xe5, 0x79, 0xa9, 0x45, 0x60, 0x53, 0x39, 0x83, 0x20, 0x1c, 0x21,
	0x21, 0x2e, 0x96, 0xd2, 0xd2, 0xcc, 0x14, 0xb0, 0xe1, 0x9c, 0x41, 0x60, 0x36, 0xc4, 0x6e, 0x66,
	0x14, 0xbb, 0x59, 0x50, 0xec, 0x66, 0x45, 0xb1, 0x9b, 0x0d, 0xc5, 0x6e, 0x76, 0xa8, 0xdd, 0x49,
	0x6c, 0x60, 0x7f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x53, 0xac, 0x77, 0x49, 0xec, 0x00,
	0x00, 0x00,
}
