// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/types.proto

package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TileMapTx struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileMapTx) Reset()         { *m = TileMapTx{} }
func (m *TileMapTx) String() string { return proto.CompactTextString(m) }
func (*TileMapTx) ProtoMessage()    {}
func (*TileMapTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_3c6a1fa4948190f4, []int{0}
}
func (m *TileMapTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileMapTx.Unmarshal(m, b)
}
func (m *TileMapTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileMapTx.Marshal(b, m, deterministic)
}
func (dst *TileMapTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileMapTx.Merge(dst, src)
}
func (m *TileMapTx) XXX_Size() int {
	return xxx_messageInfo_TileMapTx.Size(m)
}
func (m *TileMapTx) XXX_DiscardUnknown() {
	xxx_messageInfo_TileMapTx.DiscardUnknown(m)
}

var xxx_messageInfo_TileMapTx proto.InternalMessageInfo

func (m *TileMapTx) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type TileMapState struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileMapState) Reset()         { *m = TileMapState{} }
func (m *TileMapState) String() string { return proto.CompactTextString(m) }
func (*TileMapState) ProtoMessage()    {}
func (*TileMapState) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_3c6a1fa4948190f4, []int{1}
}
func (m *TileMapState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileMapState.Unmarshal(m, b)
}
func (m *TileMapState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileMapState.Marshal(b, m, deterministic)
}
func (dst *TileMapState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileMapState.Merge(dst, src)
}
func (m *TileMapState) XXX_Size() int {
	return xxx_messageInfo_TileMapState.Size(m)
}
func (m *TileMapState) XXX_DiscardUnknown() {
	xxx_messageInfo_TileMapState.DiscardUnknown(m)
}

var xxx_messageInfo_TileMapState proto.InternalMessageInfo

func (m *TileMapState) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type TileMapStateUpdate struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TileMapStateUpdate) Reset()         { *m = TileMapStateUpdate{} }
func (m *TileMapStateUpdate) String() string { return proto.CompactTextString(m) }
func (*TileMapStateUpdate) ProtoMessage()    {}
func (*TileMapStateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_3c6a1fa4948190f4, []int{2}
}
func (m *TileMapStateUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileMapStateUpdate.Unmarshal(m, b)
}
func (m *TileMapStateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileMapStateUpdate.Marshal(b, m, deterministic)
}
func (dst *TileMapStateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileMapStateUpdate.Merge(dst, src)
}
func (m *TileMapStateUpdate) XXX_Size() int {
	return xxx_messageInfo_TileMapStateUpdate.Size(m)
}
func (m *TileMapStateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TileMapStateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TileMapStateUpdate proto.InternalMessageInfo

func (m *TileMapStateUpdate) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*TileMapTx)(nil), "TileMapTx")
	proto.RegisterType((*TileMapState)(nil), "TileMapState")
	proto.RegisterType((*TileMapStateUpdate)(nil), "TileMapStateUpdate")
}

func init() { proto.RegisterFile("types/types.proto", fileDescriptor_types_3c6a1fa4948190f4) }

var fileDescriptor_types_3c6a1fa4948190f4 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0xf2, 0x5c, 0x9c, 0x21, 0x99,
	0x39, 0xa9, 0xbe, 0x89, 0x05, 0x21, 0x15, 0x42, 0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x12, 0x17, 0x0f, 0x54, 0x41, 0x70, 0x49,
	0x62, 0x49, 0x2a, 0x56, 0x35, 0x1a, 0x5c, 0x42, 0xc8, 0x6a, 0x42, 0x0b, 0x52, 0x70, 0xa8, 0x4c,
	0x62, 0x03, 0xdb, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xca, 0x7d, 0xd6, 0x8a, 0x00,
	0x00, 0x00,
}
